import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home( {website}) {
  return (
    <>
      <Head>
        <title>JMG website</title>
        <meta name="description" content="JMG website generated by" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p> 
            {  website.title }  Welcome to ARCard. 
          </p>
          
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>


      </main>
    </>
  )
}

export async function getStaticProps(context) {

 

  const res = await fetch("http://localhost:1337/website")
  const website = await res.json()


  return {
    props: {website}, // will be passed to the page component as props
  }
}